/**
 * 儿童/青少年情感原型库（0-17岁）
 * 覆盖年龄段：0-1(新生儿), 2-3(婴童), 4-6(幼童), 7-12(儿童), 13-17(青少年)
 *
 * 使用统一年龄段定义（AgeGroupRange），与 age-groups.ts 保持一致
 */

import type { EmotionArchetype } from "./types.js";
import {
  TEEN_AGE_RANGES,
  CHILD_AGE_RANGES_7_12,
  CHILD_AGE_RANGES_4_6,
  CHILD_AGE_RANGES_2_3,
  INFANT_TO_TODDLER_AGE_RANGES,
  CHILD_AND_TEEN_AGE_RANGES,
  TODDLER_AND_CHILD_AGE_RANGES,
  INFANT_TO_CHILD_AGE_RANGES,
  INFANT_TO_TEEN_AGE_RANGES,
  TODDLER_TO_TEEN_AGE_RANGES,
} from "../../../constants/age-groups.js";

export const CHILD_EMOTION_ARCHETYPE_LIBRARY: EmotionArchetype[] = [
  // ========== 类别1：自我发现（4个） ==========

  {
    id: "EA-066",
    name: "妈妈给我穿的新衣",
    category: "自我发现",
    emotionCore: "陌生 → 开心",
    moment: "妈妈给穿上新买的衣服，第一次看到镜子里不一样的自己",
    conflict: "这件衣服好奇怪，但照镜子好像还不错",
    clothingRole: "服饰=被照顾的温暖",
    visualCues: ["新衣服", "镜子", "妈妈的手", "笑容"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_TODDLER_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-067",
    name: "第一次自己选衣服",
    category: "自我发现",
    emotionCore: "犹豫 → 骄傲",
    moment: "第一次自己从衣柜里挑选出门要穿的衣服",
    conflict: "选哪件好呢？红色还是蓝色？",
    clothingRole: "服饰=自主选择的开始",
    visualCues: ["衣柜", "纠结的小手", "最终选择", "骄傲表情"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TODDLER_AND_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-068",
    name: "校服外的我",
    category: "自我发现",
    emotionCore: "拘束 → 释放",
    moment: "放学回家脱掉校服，换上自己喜欢的衣服",
    conflict: "在学校要穿校服，现在终于可以做自己了",
    clothingRole: "服饰=自我表达的出口",
    visualCues: ["脱校服", "换衣服", "释放表情", "自信姿态"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["休闲街头", "运动活力"],
    suitableAge: CHILD_AND_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-069",
    name: "变身超人和公主",
    category: "自我发现",
    emotionCore: "平凡 → 神奇",
    moment: "穿上超人斗篷或公主裙，觉得自己真的变成了那个角色",
    conflict: "无冲突，纯粹的想象和快乐",
    clothingRole: "服饰=想象力的翅膀",
    visualCues: ["角色服装", "变身动作", "开心奔跑", "想象场景"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别2：时间流逝（4个） ==========

  {
    id: "EA-070",
    name: "去年的衣服穿不下了",
    category: "时间流逝",
    emotionCore: "不舍 → 接受",
    moment: "拿出去年最喜欢的衣服，发现已经穿不下了",
    conflict: "这件裙子我最喜欢了，怎么变小了？",
    clothingRole: "服饰=成长的证据",
    visualCues: ["小衣服", "费力穿的动作", "对比", "感慨"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TODDLER_AND_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-071",
    name: "哥哥姐姐的旧衣服",
    category: "时间流逝",
    emotionCore: "好奇 → 珍惜",
    moment: "穿上哥哥姐姐传下来的衣服，觉得自己也长大了",
    conflict: "这是哥哥穿过的，现在轮到我了",
    clothingRole: "服饰=成长的传承",
    visualCues: ["旧衣服", "哥哥姐姐的照片", "穿上", "骄傲"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TODDLER_AND_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-072",
    name: "新学校的校服",
    category: "时间流逝",
    emotionCore: "紧张 → 自豪",
    moment: "第一次穿上新学校的校服，感觉自己又长大了",
    conflict: "新学校会不会喜欢我？",
    clothingRole: "服饰=新阶段的开始",
    visualCues: ["新校服", "镜子", "深呼吸", "出门"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["校园清新"],
    suitableAge: TODDLER_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-073",
    name: "童年的衣柜",
    category: "时间流逝",
    emotionCore: "怀念 → 感慨",
    moment: "整理衣柜，翻出小时候穿的可爱衣服，回忆涌上来",
    conflict: "原来我小时候穿这个啊，好可爱",
    clothingRole: "服饰=童年的时光机",
    visualCues: ["小衣服", "照片", "微笑", "感慨"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别3：人际连接（4个） ==========

  {
    id: "EA-074",
    name: "和好朋友穿一样",
    category: "人际连接",
    emotionCore: "期待 → 开心",
    moment: "和好朋友约好穿一样颜色的衣服上学",
    conflict: "无冲突，友谊的小确幸",
    clothingRole: "服饰=友谊的暗号",
    visualCues: ["两个小朋友", "同色衣服", "开心碰拳", "笑容"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TODDLER_AND_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-075",
    name: "妈妈的打扮",
    category: "人际连接",
    emotionCore: "抗拒 → 喜欢",
    moment: "被妈妈精心打扮，一开始不情愿，照镜子后很开心",
    conflict: "我不想穿这个... 咦，好像还不错？",
    clothingRole: "服饰=母爱的表达",
    visualCues: ["妈妈的梳妆", "抗拒表情", "照镜子", "惊喜"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-076",
    name: "幼儿园大合影",
    category: "人际连接",
    emotionCore: "紧张 → 开心",
    moment: "幼儿园拍集体照，大家都穿得整整齐齐",
    conflict: "要站在哪里？要不要笑？",
    clothingRole: "服饰=集体记忆的统一",
    visualCues: ["整齐的队伍", "各种小表情", "咔嚓一声", "开心散开"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["校园清新"],
    suitableAge: INFANT_TO_TODDLER_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-077",
    name: "亲子装出门",
    category: "人际连接",
    emotionCore: "害羞 → 骄傲",
    moment: "穿和爸爸妈妈一样的亲子装出门",
    conflict: "好害羞... 但感觉自己好特别",
    clothingRole: "服饰=家庭的纽带",
    visualCues: ["亲子装", "手牵手", "路人眼光", "骄傲"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["休闲街头"],
    suitableAge: INFANT_TO_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别4：意外时刻（4个） ==========

  {
    id: "EA-078",
    name: "玩泥巴弄脏新衣服",
    category: "意外时刻",
    emotionCore: "开心 → 害怕 → 被原谅",
    moment: "穿着新衣服忍不住去玩泥巴，回家怕被骂",
    conflict: "好好玩！但衣服脏了妈妈会生气吗？",
    clothingRole: "服饰=童真vs规矩的碰撞",
    visualCues: ["泥巴", "脏衣服", "害怕表情", "妈妈微笑"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-079",
    name: "鞋子穿反了",
    category: "意外时刻",
    emotionCore: "得意 → 困惑 → 好笑",
    moment: "自己穿好鞋子出门，走了好久才发现穿反了",
    conflict: "明明自己穿的，怎么不对？",
    clothingRole: "服饰=独立的小插曲",
    visualCues: ["反穿的鞋子", "走路别扭", "发现", "大笑"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_TODDLER_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-080",
    name: "水坑的诱惑",
    category: "意外时刻",
    emotionCore: "犹豫 → 放纵",
    moment: "穿着新鞋出门，遇到大水坑，忍了很久还是踩了进去",
    conflict: "妈妈说不能踩... 但它好像在叫我",
    clothingRole: "服饰=规则vs快乐的拉锯",
    visualCues: ["水坑", "犹豫的脚步", "一脚踏入", "水花四溅"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-081",
    name: "衣服上的画画",
    category: "意外时刻",
    emotionCore: "创意 → 忐忑",
    moment: "在自己衣服上画画，觉得很好看，但不确定妈妈会不会生气",
    conflict: "我觉得很漂亮，但妈妈说不能画在衣服上",
    clothingRole: "服饰=创意画布",
    visualCues: ["画笔", "衣服上的画", "忐忑表情", "展示"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TODDLER_AND_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别5：日常仪式（4个） ==========

  {
    id: "EA-082",
    name: "上学的穿衣仪式",
    category: "日常仪式",
    emotionCore: "迷糊 → 精神",
    moment: "每天早上从被窝里爬出来，选衣服穿衣服准备上学",
    conflict: "好困... 但要出门了",
    clothingRole: "服饰=新一天的开始",
    visualCues: ["被窝", "打哈欠", "穿衣服", "出门"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["校园清新", "休闲街头"],
    suitableAge: TODDLER_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-083",
    name: "周末的小公主/小王子",
    category: "日常仪式",
    emotionCore: "期待 → 满足",
    moment: "周末终于可以穿最喜欢的衣服，不用穿校服",
    conflict: "无冲突，纯粹的快乐",
    clothingRole: "服饰=自由和快乐",
    visualCues: ["衣柜", "挑选", "穿上", "转圈"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TODDLER_AND_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-084",
    name: "脱衣服睡觉",
    category: "日常仪式",
    emotionCore: "不舍 → 安心",
    moment: "今天穿了最喜欢的衣服，睡觉前舍不得脱",
    conflict: "还想穿着... 但妈妈说要换睡衣了",
    clothingRole: "服饰=一天的结束",
    visualCues: ["脱衣服", "叠好放好", "睡衣", "安心"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["居家慵懒"],
    suitableAge: INFANT_TO_TODDLER_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-085",
    name: "换季新衣",
    category: "日常仪式",
    emotionCore: "期待 → 满足",
    moment: "换季了，妈妈拿出准备好的新季节衣服",
    conflict: "夏天/冬天的衣服要收起来了",
    clothingRole: "服饰=季节的信号",
    visualCues: ["换季衣服", "试穿", "满意", "期待"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别6：蜕变逆袭（3个） ==========

  {
    id: "EA-086",
    name: "运动会的逆袭",
    category: "蜕变逆袭",
    emotionCore: "紧张 → 自信",
    moment: "穿好运动服站在起跑线上，从害怕到全力以赴",
    conflict: "我能跑赢吗？",
    clothingRole: "服饰=比赛的战袍",
    visualCues: ["运动服", "起跑线", "冲刺", "庆祝"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "动作同步",
    suitableStyles: ["运动活力"],
    suitableAge: CHILD_AND_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-087",
    name: "舞台上的我",
    category: "蜕变逆袭",
    emotionCore: "害怕 → 闪耀",
    moment: "穿上演出的服装，从排练室的胆怯到舞台上的绽放",
    conflict: "台下好多人，好紧张",
    clothingRole: "服饰=勇气的来源",
    visualCues: ["演出服", "候场紧张", "登台", "自信表演"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: TODDLER_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-088",
    name: "新学期的第一天",
    category: "蜕变逆袭",
    emotionCore: "不安 → 自信",
    moment: "穿上新学期的新衣服，走进新教室",
    conflict: "新同学会喜欢我吗？",
    clothingRole: "服饰=新开始的仪式感",
    visualCues: ["新衣服", "教室门口", "深呼吸", "微笑走进"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["校园清新", "休闲街头"],
    suitableAge: CHILD_AND_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别7：身份切换（3个） ==========

  {
    id: "EA-089",
    name: "校服 vs 周末",
    category: "身份切换",
    emotionCore: "统一 → 自由",
    moment: "周一穿校服到学校，周五放学换上自己的衣服",
    conflict: "五天统一，两天自由",
    clothingRole: "服饰=规矩与自由",
    visualCues: ["校服", "换装", "自由衣服", "奔跑"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["校园清新", "休闲街头"],
    suitableAge: CHILD_AND_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-090",
    name: "角色扮演时间",
    category: "身份切换",
    emotionCore: "日常 → 想象",
    moment: "穿上不同角色的衣服，变成医生/消防员/公主/宇航员",
    conflict: "无冲突，想象的快乐",
    clothingRole: "服饰=无限可能",
    visualCues: ["普通衣服", "角色服装", "表演", "开心"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_CHILD_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-091",
    name: "冬装变夏装",
    category: "身份切换",
    emotionCore: "厚重 → 轻盈",
    moment: "脱掉厚重的冬装外套，换上轻便的夏装",
    conflict: "终于不用穿那么多了！",
    clothingRole: "服饰=季节的释放",
    visualCues: ["厚重冬装", "脱掉", "轻便夏装", "奔跑"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别8：仪式庆典（4个） ==========

  {
    id: "EA-092",
    name: "生日的小主角",
    category: "仪式庆典",
    emotionCore: "期待 → 幸福",
    moment: "生日那天穿上特别挑选的衣服，成为全场焦点",
    conflict: "今天我是最重要的！",
    clothingRole: "服饰=生日的仪式感",
    visualCues: ["挑选衣服", "生日帽", "蛋糕", "开心"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-093",
    name: "过年的新衣服",
    category: "仪式庆典",
    emotionCore: "期待 → 喜庆",
    moment: "大年初一穿上新买的年服，给长辈拜年",
    conflict: "无冲突，过年的喜悦",
    clothingRole: "服饰=新年的祝福",
    visualCues: ["红色新衣", "拜年", "红包", "开心"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-094",
    name: "毕业啦",
    category: "仪式庆典",
    emotionCore: "不舍 → 憧憬",
    moment: "穿上学士服/毕业装，和同学们拍毕业照",
    conflict: "舍不得同学，但长大了",
    clothingRole: "服饰=成长的里程碑",
    visualCues: ["毕业服", "合影", "拥抱", "憧憬"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["校园清新"],
    suitableAge: TODDLER_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-095",
    name: "家庭聚会的盛装",
    category: "仪式庆典",
    emotionCore: "害羞 → 骄傲",
    moment: "被精心打扮去参加家庭聚会，长辈们都夸好看",
    conflict: "好多人... 但大家都说我好看",
    clothingRole: "服饰=被爱包围的感觉",
    visualCues: ["精心打扮", "长辈夸赞", "害羞低头", "开心"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: INFANT_TO_TEEN_AGE_RANGES,
    suitableGender: ["male", "female"]
  }
];
