/**
 * 情感原型库
 * 成人原型 65 个（EA-001 ~ EA-065）+ 儿童/青少年原型 30 个（EA-066 ~ EA-095）
 * 共 95 个情感原型，分 8 大类，覆盖 0-30 岁全年龄段
 */

import type { EmotionArchetype } from "./types.js";
import { CHILD_EMOTION_ARCHETYPE_LIBRARY } from "./archetype-library-child.js";
import { ALL_ADULT_AGE_RANGES, YOUNG_ADULT_AGE_RANGES, MATURE_ADULT_AGE_RANGES } from "../../../constants/age-groups.js";

/** 成人情感原型（18-30岁） */
const ADULT_EMOTION_ARCHETYPE_LIBRARY: EmotionArchetype[] = [
  // ========== 类别1：自我发现（10个） ==========
  {
    id: "EA-001",
    name: "镜子里的陌生人",
    category: "自我发现",
    emotionCore: "不确定 → 接纳",
    moment: "剪了新发型/换了新风格，第一次照镜子",
    conflict: "这真的是我吗？",
    clothingRole: "新风格的首次尝试，服饰=新身份",
    visualCues: ["镜子", "光线", "表情变化"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-002",
    name: "断舍离的瞬间",
    category: "自我发现",
    emotionCore: "犹豫 → 释怀",
    moment: "把旧衣服装进袋子，准备扔掉",
    conflict: "每件都有回忆，舍不得",
    clothingRole: "旧衣服=过去，新衣服=未来",
    visualCues: ["衣柜", "袋子", "手的动作"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-003",
    name: "第一次穿出门",
    category: "自我发现",
    emotionCore: "紧张 → 自信",
    moment: "穿上新买的衣服，出门前深呼吸",
    conflict: "会不会太夸张？别人会怎么看？",
    clothingRole: "服饰=勇气的象征",
    visualCues: ["门把手", "深呼吸", "迈出门的脚步"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-004",
    name: "试衣间的犹豫",
    category: "自我发现",
    emotionCore: "犹豫 → 决定",
    moment: "试衣间里，换了三次，不知道选哪件",
    conflict: "哪件更适合我？",
    clothingRole: "服饰=选择的困境",
    visualCues: ["试衣间镜子", "多件衣服", "纠结表情"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-005",
    name: "风格突破",
    category: "自我发现",
    emotionCore: "不安 → 惊喜",
    moment: "第一次尝试完全不同的风格",
    conflict: "我能驾驭吗？",
    clothingRole: "服饰=突破的象征",
    visualCues: ["镜子", "新旧对比", "表情变化"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-006",
    name: "找到自己的风格",
    category: "自我发现",
    emotionCore: "迷茫 → 笃定",
    moment: "试了很多风格后，终于找到适合自己的",
    conflict: "什么才是真正的我？",
    clothingRole: "服饰=自我认同",
    visualCues: ["镜子", "满意的微笑", "自信姿态"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-007",
    name: "接纳不完美",
    category: "自我发现",
    emotionCore: "挑剔 → 接纳",
    moment: "照镜子，发现衣服不完美，但决定接受",
    conflict: "必须完美吗？",
    clothingRole: "服饰=真实的自己",
    visualCues: ["镜子", "小瑕疵", "释然表情"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-008",
    name: "重新定义自己",
    category: "自我发现",
    emotionCore: "困惑 → 清晰",
    moment: "整理衣柜，决定重新定义自己的风格",
    conflict: "我想成为什么样的人？",
    clothingRole: "服饰=身份的重塑",
    visualCues: ["衣柜", "分类整理", "决心"],
    duration: "18-25秒",
    shotCount: 5,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-009",
    name: "穿上战袍",
    category: "自我发现",
    emotionCore: "忐忑 → 强大",
    moment: "重要场合前，穿上最有信心的衣服",
    conflict: "我准备好了吗？",
    clothingRole: "服饰=力量的来源",
    visualCues: ["镜子", "整理衣服", "深呼吸"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["通勤职场", "优雅知性"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-010",
    name: "做回自己",
    category: "自我发现",
    emotionCore: "压抑 → 释放",
    moment: "脱掉不舒服的正装，换上舒适的衣服",
    conflict: "为什么要伪装？",
    clothingRole: "服饰=真实vs伪装",
    visualCues: ["脱衣动作", "舒适衣服", "放松表情"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["居家慵懒", "休闲街头"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别2：时间流逝（10个） ==========
  {
    id: "EA-011",
    name: "十年前的衣服",
    category: "时间流逝",
    emotionCore: "怀念 → 释怀",
    moment: "整理衣柜，翻出十年前的衣服，试穿一下",
    conflict: "还能穿吗？我变了多少？",
    clothingRole: "服饰=时间的见证",
    visualCues: ["旧衣服", "镜子", "对比"],
    duration: "18-25秒",
    shotCount: 5,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-012",
    name: "妈妈的衣柜",
    category: "时间流逝",
    emotionCore: "好奇 → 理解",
    moment: "翻妈妈年轻时的衣服，试穿",
    conflict: "原来妈妈年轻时是这样的",
    clothingRole: "服饰=跨代连接",
    visualCues: ["老照片", "旧衣服", "镜子"],
    duration: "20-25秒",
    shotCount: 5,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["female"]
  },
  {
    id: "EA-013",
    name: "老地方新衣服",
    category: "时间流逝",
    emotionCore: "怀念 → 向前看",
    moment: "穿着新衣服回到多年前常去的地方",
    conflict: "地方没变，我变了",
    clothingRole: "服饰=成长的标记",
    visualCues: ["熟悉的场景", "新的自己"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-014",
    name: "毕业照里的衣服",
    category: "时间流逝",
    emotionCore: "怀旧 → 感慨",
    moment: "翻出毕业照，发现还留着当时的衣服",
    conflict: "那时的梦想实现了吗？",
    clothingRole: "服饰=青春的记忆",
    visualCues: ["照片", "旧衣服", "回忆"],
    duration: "18-25秒",
    shotCount: 5,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-015",
    name: "第一次约会的衣服",
    category: "时间流逝",
    emotionCore: "甜蜜 → 感慨",
    moment: "翻出第一次约会穿的衣服",
    conflict: "那时的我们还在一起吗？",
    clothingRole: "服饰=爱情的见证",
    visualCues: ["衣服", "回忆", "微笑或叹息"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["浪漫约会", "优雅知性"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-016",
    name: "孩子穿不下的衣服",
    category: "时间流逝",
    emotionCore: "不舍 → 接受",
    moment: "整理孩子的旧衣服，发现都穿不下了",
    conflict: "孩子长大了",
    clothingRole: "服饰=成长的痕迹",
    visualCues: ["小衣服", "对比", "感慨"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: MATURE_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-017",
    name: "换季整理",
    category: "时间流逝",
    emotionCore: "平静 → 感慨",
    moment: "换季整理衣柜，发现时间过得真快",
    conflict: "又一年过去了",
    clothingRole: "服饰=季节的轮回",
    visualCues: ["衣柜", "换季衣服", "时光流逝"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-018",
    name: "旧照片新造型",
    category: "时间流逝",
    emotionCore: "对比 → 自信",
    moment: "对比旧照片，发现现在的自己更好",
    conflict: "我变了吗？",
    clothingRole: "服饰=蜕变的证明",
    visualCues: ["照片", "镜子", "对比"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-019",
    name: "重回母校",
    category: "时间流逝",
    emotionCore: "怀念 → 释然",
    moment: "穿着现在的衣服回到母校",
    conflict: "我还是当年的我吗？",
    clothingRole: "服饰=时间的对比",
    visualCues: ["校园", "新衣服", "回忆"],
    duration: "18-25秒",
    shotCount: 5,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-020",
    name: "告别旧衣服",
    category: "时间流逝",
    emotionCore: "不舍 → 向前",
    moment: "把陪伴多年的衣服装箱，准备捐赠",
    conflict: "舍不得，但该放手了",
    clothingRole: "服饰=过去的告别",
    visualCues: ["旧衣服", "箱子", "告别"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别3：人际连接（10个） ==========
  {
    id: "EA-021",
    name: "电梯里的沉默",
    category: "人际连接",
    emotionCore: "尴尬 → 默契",
    moment: "电梯里遇到陌生人，眼神交汇",
    conflict: "该说什么？还是保持沉默？",
    clothingRole: "服饰=社交信号（风格相似/对比）",
    visualCues: ["电梯镜子", "眼神", "楼层数字"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "环境同步",
    suitableStyles: ["通勤职场", "休闲街头"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-022",
    name: "撞衫的尴尬",
    category: "人际连接",
    emotionCore: "尴尬 → 会心一笑",
    moment: "在公共场合发现有人穿了一样的衣服",
    conflict: "尴尬还是有趣？",
    clothingRole: "服饰=意外的连接",
    visualCues: ["眼神", "微笑", "同款衣服"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-023",
    name: "闺蜜的默契",
    category: "人际连接",
    emotionCore: "平静 → 温暖",
    moment: "和闺蜜不约而同穿了相似风格",
    conflict: "无冲突，纯粹的默契时刻",
    clothingRole: "服饰=友谊的象征",
    visualCues: ["两人并肩", "相似搭配"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["female"]
  },
  {
    id: "EA-024",
    name: "情侣装的甜蜜",
    category: "人际连接",
    emotionCore: "害羞 → 甜蜜",
    moment: "第一次穿情侣装出门",
    conflict: "会不会太高调？",
    clothingRole: "服饰=爱情的宣言",
    visualCues: ["牵手", "相似服饰", "甜蜜笑容"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["休闲街头", "浪漫约会"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-025",
    name: "陌生人的赞美",
    category: "人际连接",
    emotionCore: "意外 → 开心",
    moment: "陌生人夸赞你的衣服好看",
    conflict: "无冲突，意外的惊喜",
    clothingRole: "服饰=连接的桥梁",
    visualCues: ["对话", "微笑", "自信"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-026",
    name: "借衣服的友谊",
    category: "人际连接",
    emotionCore: "犹豫 → 信任",
    moment: "朋友借你的衣服穿",
    conflict: "会不会弄坏？",
    clothingRole: "服饰=信任的象征",
    visualCues: ["衣服", "朋友", "信任"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-027",
    name: "父母的关心",
    category: "人际连接",
    emotionCore: "不耐烦 → 温暖",
    moment: "父母说你穿太少，给你加衣服",
    conflict: "不需要，但又感动",
    clothingRole: "服饰=爱的表达",
    visualCues: ["父母", "衣服", "温暖"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-028",
    name: "同事的眼光",
    category: "人际连接",
    emotionCore: "在意 → 释然",
    moment: "穿了新衣服上班，在意同事的眼光",
    conflict: "他们会怎么看？",
    clothingRole: "服饰=社交的试探",
    visualCues: ["办公室", "眼神", "自信"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["通勤职场"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-029",
    name: "孩子的模仿",
    category: "人际连接",
    emotionCore: "惊讶 → 感动",
    moment: "发现孩子在模仿你的穿衣风格",
    conflict: "无冲突，温暖时刻",
    clothingRole: "服饰=榜样的力量",
    visualCues: ["孩子", "相似搭配", "温暖"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: MATURE_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-030",
    name: "老友重逢",
    category: "人际连接",
    emotionCore: "激动 → 感慨",
    moment: "多年未见的老友重逢，发现彼此都变了",
    conflict: "我们还是当年的我们吗？",
    clothingRole: "服饰=时间的见证",
    visualCues: ["拥抱", "对比", "感慨"],
    duration: "18-25秒",
    shotCount: 5,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别4：意外时刻（10个） ==========
  {
    id: "EA-031",
    name: "突然下雨",
    category: "意外时刻",
    emotionCore: "狼狈 → 释然",
    moment: "突然下雨，衣服被淋湿",
    conflict: "完美的造型被毁了",
    clothingRole: "服饰状态变化（干→湿）",
    visualCues: ["雨滴", "湿透的衣服", "躲雨"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-032",
    name: "迟到的早晨",
    category: "意外时刻",
    emotionCore: "焦虑 → 放弃挣扎",
    moment: "闹钟没响，迟到了，慌乱换衣服",
    conflict: "来不及了，随便穿一件",
    clothingRole: "服饰快速切换，展示多套",
    visualCues: ["时钟", "慌乱动作", "衣服散落"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "动作同步",
    suitableStyles: ["通勤职场"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-033",
    name: "咖啡洒了",
    category: "意外时刻",
    emotionCore: "懊恼 → 自嘲",
    moment: "咖啡洒在新衣服上",
    conflict: "新衣服第一次穿就毁了",
    clothingRole: "服饰=意外的受害者",
    visualCues: ["咖啡渍", "懊恼表情", "自嘲笑容"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-034",
    name: "拉链坏了",
    category: "意外时刻",
    emotionCore: "着急 → 应变",
    moment: "出门前发现拉链坏了",
    conflict: "怎么办？来不及换了",
    clothingRole: "服饰=突发状况",
    visualCues: ["拉链", "着急", "应变"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-035",
    name: "衣服穿反了",
    category: "意外时刻",
    emotionCore: "尴尬 → 好笑",
    moment: "发现衣服穿反了一整天",
    conflict: "怎么没人告诉我？",
    clothingRole: "服饰=尴尬的来源",
    visualCues: ["镜子", "发现", "笑"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-036",
    name: "意外的礼物",
    category: "意外时刻",
    emotionCore: "惊讶 → 感动",
    moment: "收到朋友送的衣服",
    conflict: "无冲突，意外的惊喜",
    clothingRole: "服饰=心意的载体",
    visualCues: ["礼物盒", "衣服", "感动"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-037",
    name: "尺码买错了",
    category: "意外时刻",
    emotionCore: "失望 → 接受",
    moment: "网购的衣服尺码不合适",
    conflict: "退货还是将就？",
    clothingRole: "服饰=期待的落差",
    visualCues: ["试穿", "镜子", "失望"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-038",
    name: "被风吹乱",
    category: "意外时刻",
    emotionCore: "狼狈 → 洒脱",
    moment: "大风把衣服和头发吹乱",
    conflict: "形象全毁了",
    clothingRole: "服饰=自然的力量",
    visualCues: ["风", "凌乱", "洒脱"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-039",
    name: "电梯门夹住衣服",
    category: "意外时刻",
    emotionCore: "惊吓 → 庆幸",
    moment: "电梯门夹住衣服",
    conflict: "会不会撕坏？",
    clothingRole: "服饰=惊险时刻",
    visualCues: ["电梯", "衣服", "惊吓"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-040",
    name: "意外的搭配",
    category: "意外时刻",
    emotionCore: "将就 → 惊喜",
    moment: "随便搭配的衣服，意外地好看",
    conflict: "无冲突，意外的发现",
    clothingRole: "服饰=意外的美",
    visualCues: ["镜子", "惊喜", "自信"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别5：日常仪式（10个） ==========
  {
    id: "EA-041",
    name: "周末的慵懒",
    category: "日常仪式",
    emotionCore: "疲惫 → 放松",
    moment: "周末早晨，换上舒适的居家服",
    conflict: "无冲突，纯粹的放松时刻",
    clothingRole: "服饰=放松的信号",
    visualCues: ["阳光", "慵懒动作", "舒适质感"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["居家慵懒"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-042",
    name: "出门前的仪式",
    category: "日常仪式",
    emotionCore: "平静 → 准备好了",
    moment: "出门前整理衣服、照镜子、深呼吸",
    conflict: "无冲突，仪式感时刻",
    clothingRole: "服饰=战袍",
    visualCues: ["镜子", "整理动作", "门把手"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-043",
    name: "回家第一件事",
    category: "日常仪式",
    emotionCore: "疲惫 → 释放",
    moment: "回家，脱掉外套，换上居家服",
    conflict: "无冲突，释放的时刻",
    clothingRole: "服饰转换=状态转换",
    visualCues: ["门", "外套", "居家服"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["通勤职场", "居家慵懒"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-044",
    name: "晨间routine",
    category: "日常仪式",
    emotionCore: "迷糊 → 清醒",
    moment: "早晨起床，换衣服，开始新的一天",
    conflict: "无冲突，日常仪式",
    clothingRole: "服饰=新一天的开始",
    visualCues: ["晨光", "换衣", "清醒"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-045",
    name: "睡前的放松",
    category: "日常仪式",
    emotionCore: "疲惫 → 安心",
    moment: "睡前换上睡衣，准备休息",
    conflict: "无冲突，放松时刻",
    clothingRole: "服饰=一天的结束",
    visualCues: ["卧室", "睡衣", "放松"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["居家慵懒"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-046",
    name: "运动前的准备",
    category: "日常仪式",
    emotionCore: "懒散 → 动力",
    moment: "换上运动服，准备出门运动",
    conflict: "不想动，但换上衣服就有动力了",
    clothingRole: "服饰=动力的来源",
    visualCues: ["运动服", "镜子", "动力"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["休闲街头"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-047",
    name: "周日的咖啡时光",
    category: "日常仪式",
    emotionCore: "平静 → 满足",
    moment: "周日下午，穿着舒适的衣服，慢慢喝咖啡",
    conflict: "无冲突，享受时刻",
    clothingRole: "服饰=舒适的象征",
    visualCues: ["咖啡", "阳光", "舒适"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["居家慵懒", "休闲街头"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-048",
    name: "整理衣柜的周末",
    category: "日常仪式",
    emotionCore: "混乱 → 有序",
    moment: "周末整理衣柜，分类归纳",
    conflict: "无冲突，整理的满足感",
    clothingRole: "服饰=生活的秩序",
    visualCues: ["衣柜", "分类", "整齐"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-049",
    name: "洗衣日",
    category: "日常仪式",
    emotionCore: "平淡 → 满足",
    moment: "洗完衣服，晾晒，闻到阳光的味道",
    conflict: "无冲突，日常的满足",
    clothingRole: "服饰=生活的日常",
    visualCues: ["晾衣", "阳光", "满足"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-050",
    name: "试穿新衣服",
    category: "日常仪式",
    emotionCore: "期待 → 满意",
    moment: "收到新买的衣服，迫不及待试穿",
    conflict: "无冲突，期待的满足",
    clothingRole: "服饰=期待的实现",
    visualCues: ["包裹", "试穿", "满意"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别6：蜕变逆袭（5个） ==========
  {
    id: "EA-051",
    name: "素人改造",
    category: "蜕变逆袭",
    emotionCore: "平凡 → 惊艳",
    moment: "素颜居家服 → 化妆换装 → 完美呈现",
    conflict: "我真的能变美吗？",
    clothingRole: "服饰=蜕变的魔法",
    visualCues: ["改造前", "改造过程", "惊艳亮相"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "动作同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-052",
    name: "自信逆袭",
    category: "蜕变逆袭",
    emotionCore: "自卑 → 自信",
    moment: "穿着不合身的旧衣服 → 换上适合的风格 → 自信满满",
    conflict: "我不是那个发光的人",
    clothingRole: "服饰=自信的来源",
    visualCues: ["低头", "镜子对比", "昂首挺胸"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-053",
    name: "前任眼里的我",
    category: "蜕变逆袭",
    emotionCore: "失意 → 洒脱",
    moment: "分手后第一次精心打扮出门，偶遇前任",
    conflict: "我要让他/她后悔吗？还是不在乎？",
    clothingRole: "服饰=最好的报复是过得好",
    visualCues: ["精心打扮", "偶遇", "洒脱微笑"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["优雅知性", "休闲街头"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-054",
    name: "重要场合的战袍",
    category: "蜕变逆袭",
    emotionCore: "紧张 → 闪耀",
    moment: "面试/演讲/约会前，换上最有把握的衣服",
    conflict: "我配得上这个场合吗？",
    clothingRole: "服饰=勇气的铠甲",
    visualCues: ["紧张准备", "换装", "自信登场"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["通勤职场", "优雅知性"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-055",
    name: "低谷后的第一套新衣",
    category: "蜕变逆袭",
    emotionCore: "灰暗 → 希望",
    moment: "经历挫折后，第一次买新衣服给自己",
    conflict: "值得吗？我配吗？",
    clothingRole: "服饰=新生的开始",
    visualCues: ["灰暗背景", "新衣服", "希望的微笑"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别7：身份切换（5个） ==========
  {
    id: "EA-056",
    name: "工作日vs周末",
    category: "身份切换",
    emotionCore: "拘束 → 释放",
    moment: "脱掉职业装，换上休闲服",
    conflict: "我终于可以做回自己了",
    clothingRole: "服饰=身份的开关",
    visualCues: ["职业装", "快速换装", "休闲服"],
    duration: "10-15秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["通勤职场", "休闲街头"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-057",
    name: "白天vs夜晚",
    category: "身份切换",
    emotionCore: "理性 → 感性",
    moment: "白天通勤装扮 → 晚上约会/派对装扮",
    conflict: "同一个我，不同的精彩",
    clothingRole: "服饰=多面的自己",
    visualCues: ["阳光", "换装转场", "霓虹灯"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "环境同步",
    suitableStyles: ["通勤职场", "浪漫约会", "优雅知性"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-058",
    name: "宅家vs出门",
    category: "身份切换",
    emotionCore: "慵懒 → 精致",
    moment: "居家睡衣 → 精心打扮出门",
    conflict: "不想出门 → 出门后真香",
    clothingRole: "服饰=状态切换器",
    visualCues: ["睡衣", "化妆换装", "精致出门"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "动作同步",
    suitableStyles: ["居家慵懒", "所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-059",
    name: "角色扮演的一天",
    category: "身份切换",
    emotionCore: "好奇 → 沉浸",
    moment: "尝试完全不同风格的穿搭，体验另一种人生",
    conflict: "这还是我吗？好像也不错",
    clothingRole: "服饰=平行宇宙的入口",
    visualCues: ["原风格", "新风格", "惊喜表情"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-060",
    name: "季节切换",
    category: "身份切换",
    emotionCore: "告别 → 期待",
    moment: "收起夏装，换上秋装（或反之）",
    conflict: "夏天结束了，但秋天也很美",
    clothingRole: "服饰=季节的使者",
    visualCues: ["收衣服", "换衣服", "新季节场景"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },

  // ========== 类别8：仪式庆典（5个） ==========
  {
    id: "EA-061",
    name: "生日穿搭",
    category: "仪式庆典",
    emotionCore: "期待 → 幸福",
    moment: "精心挑选生日当天的穿搭",
    conflict: "今天要特别一点",
    clothingRole: "服饰=特别日子的仪式感",
    visualCues: ["挑选衣服", "精心打扮", "蛋糕/礼物"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-062",
    name: "节日盛装",
    category: "仪式庆典",
    emotionCore: "平淡 → 喜庆",
    moment: "春节/圣诞/新年，穿上节日限定的盛装",
    conflict: "要让今天不一样",
    clothingRole: "服饰=节日的仪式感",
    visualCues: ["节日元素", "盛装", "喜悦"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "环境同步",
    suitableStyles: ["所有风格"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-063",
    name: "第一次约会",
    category: "仪式庆典",
    emotionCore: "紧张 → 甜蜜",
    moment: "第一次约会的穿搭准备",
    conflict: "穿什么才能留下好印象？",
    clothingRole: "服饰=心意的表达",
    visualCues: ["试穿多套", "最终确定", "出门"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["浪漫约会", "优雅知性", "休闲街头"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-064",
    name: "毕业典礼",
    category: "仪式庆典",
    emotionCore: "不舍 → 憧憬",
    moment: "穿上学士服/毕业装，拍毕业照",
    conflict: "学生时代结束了，未来会怎样？",
    clothingRole: "服饰=人生节点的见证",
    visualCues: ["学士服", "抛帽子", "合影"],
    duration: "15-20秒",
    shotCount: 4,
    syncMode: "情绪同步",
    suitableStyles: ["所有风格"],
    suitableAge: YOUNG_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  },
  {
    id: "EA-065",
    name: "婚礼嘉宾",
    category: "仪式庆典",
    emotionCore: "期待 → 感动",
    moment: "参加朋友婚礼，精心挑选得体的穿搭",
    conflict: "要美但不能抢新娘风头",
    clothingRole: "服饰=祝福的载体",
    visualCues: ["挑选", "婚礼现场", "感动"],
    duration: "12-18秒",
    shotCount: 3,
    syncMode: "情绪同步",
    suitableStyles: ["优雅知性", "浪漫约会"],
    suitableAge: ALL_ADULT_AGE_RANGES,
    suitableGender: ["male", "female"]
  }
];

/** 合并后的完整情感原型库（95个） */
export const EMOTION_ARCHETYPE_LIBRARY: EmotionArchetype[] = [
  ...ADULT_EMOTION_ARCHETYPE_LIBRARY,
  ...CHILD_EMOTION_ARCHETYPE_LIBRARY,
];
