/**
 * 脚本数据库脏数据修复映射规则
 * 将 175 种脏数据映射到 25 种统一字典值
 */

import { CLOTHING_STYLE_CATEGORY, type ClothingStyleCategory } from "./style-atmosphere-dict.js";

/**
 * 映射规则：脏数据 → 字典值
 *
 * 映射原则：
 * 1. 精确匹配优先（如"街头休闲风" → "街头潮流"）
 * 2. 关键词匹配次之（如包含"机能" → "酷飒"）
 * 3. 复合风格取主导风格（如"运动休闲/舒适穿搭" → "运动休闲"）
 * 4. 无法匹配的默认到"休闲"
 */
export const DIRTY_STYLE_TO_CLEAN_MAP: Record<string, ClothingStyleCategory> = {
  // ===== 街头潮流 =====
  "街头休闲风": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "街头撞色风": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "街头机能": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "街头机能风": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "街头运动风": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "Y2K街头休闲": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "Y2K街头风": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "Y2K街头混搭": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "Y2K工装街头风": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "Y2K复古风": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "Y2K风/牛仔混搭/街头感": CLOTHING_STYLE_CATEGORY.STREET_TREND,
  "国潮风格": CLOTHING_STYLE_CATEGORY.STREET_TREND,

  // ===== 日系清新 =====
  "日系清新风": CLOTHING_STYLE_CATEGORY.JAPANESE_FRESH,
  "日系简约风": CLOTHING_STYLE_CATEGORY.JAPANESE_FRESH,
  "日系甜美风": CLOTHING_STYLE_CATEGORY.JAPANESE_FRESH,
  "日系居家甜美": CLOTHING_STYLE_CATEGORY.JAPANESE_FRESH,
  "自然田园/日系清新": CLOTHING_STYLE_CATEGORY.JAPANESE_FRESH,
  "自然田园风": CLOTHING_STYLE_CATEGORY.JAPANESE_FRESH,

  // ===== 韩系精致 =====
  "韩系精致风": CLOTHING_STYLE_CATEGORY.KOREA_EXQUISITE,

  // ===== 运动休闲 =====
  "运动休闲": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动休闲风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动休闲街头风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动休闲/机能风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动休闲/舒适穿搭": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动休闲/舒适通勤": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动休闲/轻户外": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动叠穿风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动机能风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动活力风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "运动街头风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "活力运动风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "休闲运动风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "休闲街头风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "休闲街头风/复古工装": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "休闲舒适风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "休闲时尚风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "休闲度假风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "休闲通勤风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "户外休闲风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "轻户外休闲": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "都市休闲风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "都市休闲": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "都市运动风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "都市轻户外": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "都市轻户外风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "校园休闲风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "校园运动机能风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "校园活力风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "校园轻运动风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "清新校园风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "简约运动校园风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "简约运动风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "青春机能风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "阳光活力风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "元气运动休闲风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "Athleisure": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "Sporty": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,

  // ===== 慵懒风 =====
  "慵懒家居风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "慵懒家居风/文艺森系风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "慵懒文艺风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "慵懒春日风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "慵懒知性风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "慵懒自然风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "慵懒通勤/春日松弛风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "自然慵懒风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "自然慵懒通勤风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "松弛机能风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,
  "通勤松弛风": CLOTHING_STYLE_CATEGORY.LAZY_STYLE,

  // ===== 复古 =====
  "复古学院风": CLOTHING_STYLE_CATEGORY.RETRO,
  "复古街头运动风": CLOTHING_STYLE_CATEGORY.RETRO,
  "复古街头风": CLOTHING_STYLE_CATEGORY.RETRO,
  "复古运动混搭": CLOTHING_STYLE_CATEGORY.RETRO,
  "复古运动风": CLOTHING_STYLE_CATEGORY.RETRO,
  "温柔轻复古风": CLOTHING_STYLE_CATEGORY.RETRO,

  // ===== 简约 =====
  "极简主义": CLOTHING_STYLE_CATEGORY.MINIMALIST,
  "极简风": CLOTHING_STYLE_CATEGORY.MINIMALIST,
  "简约清新风": CLOTHING_STYLE_CATEGORY.MINIMALIST,
  "简约通勤": CLOTHING_STYLE_CATEGORY.MINIMALIST,
  "简约通勤风": CLOTHING_STYLE_CATEGORY.MINIMALIST,
  "自然简约风": CLOTHING_STYLE_CATEGORY.MINIMALIST,
  "都市简约风": CLOTHING_STYLE_CATEGORY.MINIMALIST,
  "中性极简风": CLOTHING_STYLE_CATEGORY.MINIMALIST,

  // ===== 清新 =====
  "清新约会风": CLOTHING_STYLE_CATEGORY.FRESH,
  "清透校园风": CLOTHING_STYLE_CATEGORY.FRESH,
  "实用户外/清透校园风": CLOTHING_STYLE_CATEGORY.FRESH,

  // ===== 优雅 =====
  "优雅知性风": CLOTHING_STYLE_CATEGORY.ELEGANT,
  "优雅知性风/通勤职场风": CLOTHING_STYLE_CATEGORY.ELEGANT,
  "都市轻熟风": CLOTHING_STYLE_CATEGORY.ELEGANT,

  // ===== 通勤 =====
  "通勤极简风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "通勤知性风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "通勤精致风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "通勤职场风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "通勤职场风/文艺知性风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "实用主义通勤": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "实用主义通勤风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "实用通勤风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "现代通勤/实用主义": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "现代通勤/实用工装": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "现代通勤风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "都市通勤风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "都市通勤力量风": CLOTHING_STYLE_CATEGORY.COMMUTE,

  // ===== 居家 =====
  "浪漫居家风": CLOTHING_STYLE_CATEGORY.HOME,

  // ===== 商务 =====
  "职场精英风": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "职场精英/简约高级": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "职场通勤风": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "职场通勤风/极简都市风": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "极简职场/高腰线通勤风": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "极简职场风": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "现代职场风": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "现代权力穿搭": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "结构感通勤风": CLOTHING_STYLE_CATEGORY.BUSINESS,
  "知性通勤/力量感剪裁": CLOTHING_STYLE_CATEGORY.BUSINESS,

  // ===== 时尚 =====
  "时尚/复古学院风": CLOTHING_STYLE_CATEGORY.FASHION,
  "时尚休闲/甜酷风": CLOTHING_STYLE_CATEGORY.FASHION,

  // ===== 古风 =====
  "国风雅致": CLOTHING_STYLE_CATEGORY.CHINESE_CLASSICAL,
  "传统中式风": CLOTHING_STYLE_CATEGORY.CHINESE_CLASSICAL,

  // ===== 甜美 =====
  "甜美亲子风": CLOTHING_STYLE_CATEGORY.SWEET,
  "甜美可爱风": CLOTHING_STYLE_CATEGORY.SWEET,
  "亲子装风格": CLOTHING_STYLE_CATEGORY.SWEET,
  "浪漫主义/日系甜美": CLOTHING_STYLE_CATEGORY.SWEET,

  // ===== 酷飒 =====
  "甜酷休闲风": CLOTHING_STYLE_CATEGORY.COOL,
  "甜酷机能风": CLOTHING_STYLE_CATEGORY.COOL,
  "甜酷校园风": CLOTHING_STYLE_CATEGORY.COOL,
  "甜酷街头风": CLOTHING_STYLE_CATEGORY.COOL,
  "机能休闲": CLOTHING_STYLE_CATEGORY.COOL,
  "机能实用风": CLOTHING_STYLE_CATEGORY.COOL,
  "机能户外风": CLOTHING_STYLE_CATEGORY.COOL,
  "机能街头风": CLOTHING_STYLE_CATEGORY.COOL,
  "机能运动/科技街头": CLOTHING_STYLE_CATEGORY.COOL,
  "机能运动/都市休闲": CLOTHING_STYLE_CATEGORY.COOL,
  "机能运动风": CLOTHING_STYLE_CATEGORY.COOL,
  "城市机能风": CLOTHING_STYLE_CATEGORY.COOL,
  "都市机能风": CLOTHING_STYLE_CATEGORY.COOL,
  "工装机能风": CLOTHING_STYLE_CATEGORY.COOL,
  "轻户外机能": CLOTHING_STYLE_CATEGORY.COOL,
  "轻运动街头风": CLOTHING_STYLE_CATEGORY.COOL,

  // ===== 文艺 =====
  "文艺森系风": CLOTHING_STYLE_CATEGORY.ARTISTIC,
  "文艺森系风/轻通勤": CLOTHING_STYLE_CATEGORY.ARTISTIC,

  // ===== 其他（需要特殊处理的品牌、单品等） =====
  // 品牌相关 → 映射到对应风格
  "Champion连帽外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "特步儿童拼色外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "黑色连帽拉链外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "黑色连帽运动外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "深灰拼接条纹短外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "深灰条纹领短外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "假两件条纹领短外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "绿色连帽软壳外套": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "云白色系": CLOTHING_STYLE_CATEGORY.MINIMALIST,

  // 户外相关 → 运动休闲
  "户外探险风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "户外机能": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "户外机能风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,
  "自然户外风": CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL,

  // 工装相关 → 酷飒
  "实用工装风": CLOTHING_STYLE_CATEGORY.COOL,
  "工装极简风": CLOTHING_STYLE_CATEGORY.COOL,
  "工装精致化": CLOTHING_STYLE_CATEGORY.COOL,
  "工装风/实用主义/大地色系": CLOTHING_STYLE_CATEGORY.COOL,

  // 欧美风格 → 街头潮流
  "欧美随性": CLOTHING_STYLE_CATEGORY.STREET_TREND,

  // 现代都市 → 通勤
  "现代简约风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "都市现代": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "都市现代风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "都市知性风": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "都市轻职场": CLOTHING_STYLE_CATEGORY.COMMUTE,
  "都市轻职场风": CLOTHING_STYLE_CATEGORY.COMMUTE,

  // 温柔/柔和 → 柔和
  "温柔清新风": CLOTHING_STYLE_CATEGORY.SOFT,
  "反差叠穿/柔美通勤": CLOTHING_STYLE_CATEGORY.SOFT,

  // 反差叠穿 → 时尚
  "反差叠穿": CLOTHING_STYLE_CATEGORY.FASHION,
  "反差叠穿/休闲通勤": CLOTHING_STYLE_CATEGORY.FASHION,
  "同色系叠穿风": CLOTHING_STYLE_CATEGORY.FASHION,

  // 极简干练 → 利落
  "极简干练风": CLOTHING_STYLE_CATEGORY.SHARP,
};

/**
 * 无法映射的默认值
 */
export const DEFAULT_CLEAN_STYLE: ClothingStyleCategory = CLOTHING_STYLE_CATEGORY.CASUAL;

/**
 * 清洗脏数据风格值
 */
export function cleanDirtyStyle(dirtyStyle: string): ClothingStyleCategory {
  // 1. 精确匹配
  if (DIRTY_STYLE_TO_CLEAN_MAP[dirtyStyle]) {
    return DIRTY_STYLE_TO_CLEAN_MAP[dirtyStyle];
  }

  // 2. 关键词匹配（针对复合风格）
  const styleStr = dirtyStyle.toLowerCase();

  // 关键词映射
  if (styleStr.includes("街头") || styleStr.includes("潮流") || styleStr.includes("y2k") || styleStr.includes("国潮")) {
    return CLOTHING_STYLE_CATEGORY.STREET_TREND;
  }
  if (styleStr.includes("日系") || styleStr.includes("田园")) {
    return CLOTHING_STYLE_CATEGORY.JAPANESE_FRESH;
  }
  if (styleStr.includes("韩系")) {
    return CLOTHING_STYLE_CATEGORY.KOREA_EXQUISITE;
  }
  if (styleStr.includes("运动") || styleStr.includes("户外") || styleStr.includes("休闲")) {
    return CLOTHING_STYLE_CATEGORY.SPORTS_CASUAL;
  }
  if (styleStr.includes("慵懒") || styleStr.includes("松弛")) {
    return CLOTHING_STYLE_CATEGORY.LAZY_STYLE;
  }
  if (styleStr.includes("复古")) {
    return CLOTHING_STYLE_CATEGORY.RETRO;
  }
  if (styleStr.includes("简约") || styleStr.includes("极简")) {
    return CLOTHING_STYLE_CATEGORY.MINIMALIST;
  }
  if (styleStr.includes("优雅") || styleStr.includes("知性")) {
    return CLOTHING_STYLE_CATEGORY.ELEGANT;
  }
  if (styleStr.includes("通勤") || styleStr.includes("职场") || styleStr.includes("商务")) {
    return CLOTHING_STYLE_CATEGORY.COMMUTE;
  }
  if (styleStr.includes("甜美") || styleStr.includes("浪漫")) {
    return CLOTHING_STYLE_CATEGORY.SWEET;
  }
  if (styleStr.includes("机能") || styleStr.includes("工装") || styleStr.includes("酷")) {
    return CLOTHING_STYLE_CATEGORY.COOL;
  }
  if (styleStr.includes("文艺") || styleStr.includes("森系")) {
    return CLOTHING_STYLE_CATEGORY.ARTISTIC;
  }
  if (styleStr.includes("古风") || styleStr.includes("中式") || styleStr.includes("国风")) {
    return CLOTHING_STYLE_CATEGORY.CHINESE_CLASSICAL;
  }

  // 3. 默认值
  return DEFAULT_CLEAN_STYLE;
}