import type { ReverseStoryboardLibraryItem } from "./reverse-storyboard-report.js";

export const REVERSE_STORYBOARD_LIBRARY_API_VERSION = "AT49-04.v1";
export const REVERSE_STORYBOARD_LIBRARY_ROUTE_PREFIX = "/reverse-storyboard-library";
export const REVERSE_STORYBOARD_SHARED_PIPELINE_SOURCE_TYPES = ["video_url"] as const;
export const REVERSE_STORYBOARD_LIBRARY_API_INVARIANTS = [
  "Reverse storyboard library keeps user-facing CRUD under a dedicated route prefix.",
  "Content edits must always keep report payloads synchronized with the latest structured storyboard shape.",
  "Storyboard library version history remains separate from legacy script-library versions.",
  "Entries generated by reverse/parse-v2(video_url) and hot-trend batch reverse share the same sourceType and report shape.",
] as const;

export type ReverseStoryboardSharedPipelineSourceType = (typeof REVERSE_STORYBOARD_SHARED_PIPELINE_SOURCE_TYPES)[number];

export interface ReverseStoryboardLibraryVersionRecord {
  readonly id: string;
  readonly itemId: string;
  readonly userId: string;
  readonly version: number;
  readonly title: string;
  readonly summary: string;
  readonly tags: readonly string[];
  readonly sourceType: ReverseStoryboardLibraryItem["sourceType"];
  readonly sourceMeta: ReverseStoryboardLibraryItem["sourceMeta"];
  readonly report: ReverseStoryboardLibraryItem["report"];
  readonly content: string;
  readonly createdAt: number;
}

export interface ReverseStoryboardLibraryRecordDto extends ReverseStoryboardLibraryItem {
  readonly currentVersion: number;
}

export function createReverseStoryboardLibraryVersionRecord(input: {
  id: string;
  item: ReverseStoryboardLibraryItem;
  version: number;
  createdAt: number;
}): ReverseStoryboardLibraryVersionRecord {
  return {
    id: input.id,
    itemId: input.item.id,
    userId: input.item.userId,
    version: input.version,
    title: input.item.title,
    summary: input.item.summary,
    tags: [...input.item.tags],
    sourceType: input.item.sourceType,
    sourceMeta: {
      videoUrl: input.item.sourceMeta.videoUrl,
      filename: input.item.sourceMeta.filename,
      mimeType: input.item.sourceMeta.mimeType,
      duration: input.item.sourceMeta.duration,
    },
    report: input.item.report,
    content: input.item.content,
    createdAt: input.createdAt,
  };
}
